//
// Created by joaqo on 5/2/21.
//

#ifndef TP_TALLER_DE_PROGRAMACION_FIUBA_ACTUALIZABLE_HPP
#define TP_TALLER_DE_PROGRAMACION_FIUBA_ACTUALIZABLE_HPP


class Actualizable {

};


#endif //TP_TALLER_DE_PROGRAMACION_FIUBA_ACTUALIZABLE_HPP
