#ifndef TP_TALLER_DE_PROGRAMACION_FIUBA_CONSTANTES_HPP
#define TP_TALLER_DE_PROGRAMACION_FIUBA_CONSTANTES_HPP

const int ANCHO_FONDO = 8177;
#define MAX_CONEXIONES 4

#endif //TP_TALLER_DE_PROGRAMACION_FIUBA_CONSTANTES_HPP
