#ifndef TP_TALLER_DE_PROGRAMACION_FIUBA_CONSTANTES_HPP
#define TP_TALLER_DE_PROGRAMACION_FIUBA_CONSTANTES_HPP

const int ANCHO_FONDO = 8177;
#define IZQUIERDA -1
#define DERECHA 1
#define MAX_CONEXIONES 4
#define SIN_JUGAR -1
#define LARGO_IP 20

#endif //TP_TALLER_DE_PROGRAMACION_FIUBA_CONSTANTES_HPP
